version: '2'
services:
  minecraft:
    build: .
    ports:
     - "25565:25565"
     - "25565:25565/udp"
    volumes:
     - ./data:/opt/minecraft/world
    environment:
      - GAMEMODE=0
      - MOTD=Welcome to the adesso Minecraft Server
      - JVM_MEMORY=2G